language: python
python:
- pypy
- 2.6
- 2.7
- 3.3
install:
- pip install pytest pytest-cov httpretty pep8 coveralls
- pip install -e .
script:
- py.test --cov earthreader --durations=10
- python -c "from earthreader.web import app; print app.test_client().get('/').data" | python tests/html5check.py -h
- pep8
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    on_success: change
    on_failure: always
