language: python
python:
- 2.6
- 2.7
- 3.3
install:
- pip install pytest pytest-cov coveralls
- pip install -e .
script:
- py.test --cov earthreader --durations=10
- python web/html5check.py web/index.html
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    on_success: change
    on_failure: always
