language: python
python:
- pypy
- 2.6
- 2.7
- 3.3
install:
- pip install pytest pytest-cov pep8 coveralls
- pip install -e .
script:
- py.test --cov earthreader --durations=10
- if [ `python -c 'import sys; print(sys.version_info[0])'` != '3' ]; then python -c "from earthreader.web import app; print(app.test_client().get('/').data)" | python tests/html5check.py -h; fi
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then pep8; fi
after_success:
- coveralls
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    on_success: change
    on_failure: always
